apiVersion: v1
kind: Pod
metadata:
  name: testpod-annotation
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name : nginx
    image : nginx:1.14
  nodeSelector:
    storage: ssd
