apiVersion: v1
kind: Service
metadata:
  name: webui-svc-nodeport
spec:
  type: NodePort
  #clusterIp:
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30200
