apiVersion: v1
kind: Service
metadata:
  name: webui-svc-headless
spec:
  type: ClusterIP
  clusterIp: None # 이렇게 지정하면 헤드리스 서비스 
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
