apiVersion: v1
kind: Pod
metadata:
  name: genid-stone
spec:
  containers:
  - name : fakeid-generator
    image : smlinux/genid:env
    env:
    - name : INTERVAL
      valueFrom:
        secretKeyRef:
          name: jkkim-secret
          key: INTERVAL
    volumeMounts:
    - name: html
      mountPath: /webdata
  - image: nginx:1.14
    name : web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
  volumes:
  - name: html
    emptyDir: {}
