apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jpetstore-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jpetstore
  template:
    metadata:
      name: tomcat-container
      labels:
         app: jpetstore
    spec:
      containers:
      - name: tomcat-container
        image: bangmaroo/tomcat-jpetstore:1.0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jpetstore
  name: jpetstore-svc
spec:
  ports:
    - port: 8088
      targetPort: 8080
      nodePort: 30088
  selector:
    app: jpetstore
  type: NodePort
