apiVersion: v1
kind: Pod
metadata:
  name: web-volume
spec:
  containers:
  - image: nginx:1.14
    name : web-server
    ports:
    - containerPort: 80
    volumeMounts:
            #    - name: config
            #      mountPath: /etc/nginx/conf.d
            #      readOnly: true      
    - name: index
      mountPath: /usr/share/nginx/html
      readOnly: true      
  volumes:
  - name: config
    #    configMap:
    #  name: jkkim-config
    #  items:
    #  - key: nginx-config.conf
    #    path: nginx-config.conf
  - name: index 
    configMap:
      name: jkkim-config
      items:
      - key: index.html
        path: index.html
